INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'TMI','火險保費','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'F09','暫付火險保費','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'F25','催收款項－火險費用','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'F07','暫付法務費 ','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'F24','催收款項－法務費用','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'F10','帳管費','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'F29','契變手續費','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'Z10','短期擔保放款 ','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'Z20','中期擔保放款','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'Z30','長期擔保放款','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'Z40','三十年房貸','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'IC1','短擔息','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'IC2','中擔息','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'IC3','長擔息','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'IC4','三十年房貸息','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'YOP','清償違約金','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'TAV','暫收款－可抵繳','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'TLD','暫收款－放款部專戶','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'T10','債協暫收款－收款專戶','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'TCK','暫收款－支票','Y')
INSERT INTO "CdCode" ("DefCode","DefType","Code","Item","Enable") VALUES ('AcctCode',6,'340','三十年房貸','Y')